/**
 * Monaco custom themes — « SUXAI Atelier » Dark + Light
 * ------------------------------------------------------
 * v3.0 — port du Monaco theme livré dans le bundle Claude Design
 * (suxaia/project/monaco-theme.js). Direction : warm-espresso bg
 * #26201a, ivoire-warm fg, accents bronze (#b8784a) + honey
 * (#d4a247) + sage (#8fa86c) + terra (#c75c3e). 6-rank bracket
 * pair coloring (cuivre/miel/sauge/lavande/ciel/orange) — chaque
 * niveau distinct mais tous accordés à la palette d'atelier.
 *
 * Usage : `defineSuxaiThemes(monaco); monaco.editor.setTheme(name);`
 * où `name` ∈ `'suxai-dark' | 'suxai-light'`.
 */
import type * as MonacoNS from 'monaco-editor';

export const SUXAI_DARK = 'suxai-dark' as const;
export const SUXAI_LIGHT = 'suxai-light' as const;

export function defineSuxaiThemes(
  monaco: typeof MonacoNS,
): void {
  monaco.editor.defineTheme(SUXAI_DARK, {
    base: 'vs-dark',
    inherit: true,
    rules: [
      { token: '',                    foreground: 'd9cfb9', background: '26201a' },
      { token: 'comment',             foreground: '7d7060', fontStyle: 'italic' },
      { token: 'comment.doc',         foreground: '8a7d6a', fontStyle: 'italic' },
      { token: 'string',              foreground: 'b8c489' },
      { token: 'string.escape',       foreground: 'd4a247' },
      { token: 'string.regex',        foreground: 'c8a878' },
      { token: 'number',              foreground: 'd4a247' },
      { token: 'constant.numeric',    foreground: 'd4a247' },
      { token: 'constant.language',   foreground: 'd4a247' },
      { token: 'constant',            foreground: 'd4a247' },
      { token: 'constant.boolean',    foreground: 'd4a247' },
      { token: 'variable',            foreground: 'e6dcc8' },
      { token: 'variable.parameter',  foreground: 'd8b890', fontStyle: 'italic' },
      { token: 'variable.language',   foreground: 'c8835a' },
      { token: 'keyword',             foreground: 'c8835a' },
      { token: 'keyword.control',     foreground: 'c8835a' },
      { token: 'keyword.operator',    foreground: 'a89a82' },
      { token: 'storage',             foreground: 'c8835a' },
      { token: 'storage.type',        foreground: 'b09bc4' },
      { token: 'function',            foreground: 'e0a872' },
      { token: 'entity.name.function', foreground: 'e0a872' },
      { token: 'entity.name.class',   foreground: 'd4a247' },
      { token: 'class',               foreground: 'd4a247' },
      { token: 'entity.name.type',    foreground: 'b09bc4' },
      { token: 'type',                foreground: 'b09bc4' },
      { token: 'type.identifier',     foreground: 'b09bc4' },
      { token: 'interface',           foreground: 'b09bc4' },
      { token: 'namespace',           foreground: 'b09bc4' },
      { token: 'entity.name.tag',     foreground: 'c8835a' },
      { token: 'tag',                 foreground: 'c8835a' },
      { token: 'meta.tag',            foreground: 'c8835a' },
      { token: 'attribute.name',      foreground: 'd4a247', fontStyle: 'italic' },
      { token: 'entity.other.attribute-name', foreground: 'd4a247', fontStyle: 'italic' },
      { token: 'attribute.value',     foreground: 'b8c489' },
      { token: 'support.function',    foreground: 'e0a872' },
      { token: 'support.class',       foreground: 'b09bc4' },
      { token: 'support.type',        foreground: 'b09bc4' },
      { token: 'punctuation',         foreground: '8a7d6a' },
      { token: 'delimiter',           foreground: 'a89a82' },
      { token: 'operator',            foreground: 'a89a82' },
      { token: 'meta.bracket',        foreground: 'a89a82' },
      { token: 'regexp',              foreground: 'c8a878' },
      { token: 'markup.heading',      foreground: 'd4a247', fontStyle: 'bold' },
      { token: 'markup.bold',         fontStyle: 'bold' },
      { token: 'markup.italic',       fontStyle: 'italic' },
      { token: 'invalid',             foreground: 'c75c3e', fontStyle: 'underline' },
    ],
    colors: {
      'editor.background':                       '#26201a',
      'editor.foreground':                       '#d9cfb9',
      'editor.lineHighlightBackground':          '#2e271f',
      'editor.lineHighlightBorder':              '#00000000',
      'editor.selectionBackground':              '#7a4f2e60',
      'editor.inactiveSelectionBackground':      '#7a4f2e30',
      'editor.selectionHighlightBackground':     '#7a4f2e30',
      'editor.findMatchBackground':              '#d4a24750',
      'editor.findMatchHighlightBackground':     '#d4a24725',
      'editor.wordHighlightBackground':          '#b8784a25',
      'editor.wordHighlightStrongBackground':    '#b8784a40',
      'editorCursor.foreground':                 '#d4a247',
      'editorWhitespace.foreground':             '#3a3027',
      'editorIndentGuide.background':            '#332a22',
      'editorIndentGuide.activeBackground':      '#5a4a39',
      'editorIndentGuide.background1':           '#332a22',
      'editorIndentGuide.activeBackground1':     '#5a4a39',
      'editorLineNumber.foreground':             '#5a4a39',
      'editorLineNumber.activeForeground':       '#d4a247',
      'editorRuler.foreground':                  '#332a22',
      'editorBracketMatch.background':           '#b8784a30',
      'editorBracketMatch.border':               '#b8784a',
      'editorBracketHighlight.foreground1':      '#b8784a',
      'editorBracketHighlight.foreground2':      '#d4a247',
      'editorBracketHighlight.foreground3':      '#8fa86c',
      'editorBracketHighlight.foreground4':      '#b09bc4',
      'editorBracketHighlight.foreground5':      '#6f9bbf',
      'editorBracketHighlight.foreground6':      '#c8835a',
      'editorBracketHighlight.unexpectedBracket.foreground': '#c75c3e',
      'editorGutter.background':                 '#26201a',
      'editorGutter.modifiedBackground':         '#d4a247',
      'editorGutter.addedBackground':            '#8fa86c',
      'editorGutter.deletedBackground':          '#c75c3e',
      'editorOverviewRuler.modifiedForeground':  '#d4a247cc',
      'editorOverviewRuler.addedForeground':     '#8fa86ccc',
      'editorOverviewRuler.deletedForeground':   '#c75c3ecc',
      'editorOverviewRuler.border':              '#00000000',
      'editorWidget.background':                 '#1f1a16',
      'editorWidget.border':                     '#42362980',
      'editorSuggestWidget.background':          '#1f1a16',
      'editorSuggestWidget.border':              '#423629',
      'editorSuggestWidget.selectedBackground':  '#3a3027',
      'editorSuggestWidget.highlightForeground': '#d4a247',
      'editorHoverWidget.background':            '#1f1a16',
      'editorHoverWidget.border':                '#423629',
      'minimap.background':                      '#26201a',
      'minimap.selectionHighlight':              '#d4a24788',
      'scrollbar.shadow':                        '#00000000',
      'scrollbarSlider.background':              '#5a4a3960',
      'scrollbarSlider.hoverBackground':         '#7a684f',
      'scrollbarSlider.activeBackground':        '#9a8666',
      'diffEditor.insertedTextBackground':       '#8fa86c20',
      'diffEditor.removedTextBackground':        '#c75c3e25',
      'diffEditor.insertedLineBackground':       '#8fa86c12',
      'diffEditor.removedLineBackground':        '#c75c3e15',
    },
  });

  monaco.editor.defineTheme(SUXAI_LIGHT, {
    base: 'vs',
    inherit: true,
    rules: [
      { token: '',                    foreground: '3a2e21', background: 'faf5ea' },
      { token: 'comment',             foreground: '8a7860', fontStyle: 'italic' },
      { token: 'string',              foreground: '5a7838' },
      { token: 'string.escape',       foreground: '94532c' },
      { token: 'number',              foreground: '94532c' },
      { token: 'constant.numeric',    foreground: '94532c' },
      { token: 'constant.language',   foreground: '94532c' },
      { token: 'constant',            foreground: '94532c' },
      { token: 'variable',            foreground: '3a2e21' },
      { token: 'variable.parameter',  foreground: '7a4a26', fontStyle: 'italic' },
      { token: 'keyword',             foreground: '94532c' },
      { token: 'keyword.control',     foreground: '94532c' },
      { token: 'storage',             foreground: '94532c' },
      { token: 'storage.type',        foreground: '6f4a8e' },
      { token: 'function',            foreground: '8a5a2a' },
      { token: 'entity.name.function', foreground: '8a5a2a' },
      { token: 'entity.name.class',   foreground: '8a5a2a' },
      { token: 'class',               foreground: '8a5a2a' },
      { token: 'entity.name.type',    foreground: '6f4a8e' },
      { token: 'type',                foreground: '6f4a8e' },
      { token: 'type.identifier',     foreground: '6f4a8e' },
      { token: 'interface',           foreground: '6f4a8e' },
      { token: 'tag',                 foreground: '94532c' },
      { token: 'attribute.name',      foreground: '94532c', fontStyle: 'italic' },
      { token: 'attribute.value',     foreground: '5a7838' },
      { token: 'punctuation',         foreground: '8a7860' },
      { token: 'delimiter',           foreground: '8a7860' },
      { token: 'operator',            foreground: '8a7860' },
      { token: 'regexp',              foreground: 'a04f7e' },
      { token: 'invalid',             foreground: 'a04020', fontStyle: 'underline' },
    ],
    colors: {
      'editor.background':                       '#faf5ea',
      'editor.foreground':                       '#3a2e21',
      'editor.lineHighlightBackground':          '#f0e6d2',
      'editor.lineHighlightBorder':              '#00000000',
      'editor.selectionBackground':              '#d4a24745',
      'editor.inactiveSelectionBackground':      '#d4a24722',
      'editorCursor.foreground':                 '#94532c',
      'editorLineNumber.foreground':             '#b8a685',
      'editorLineNumber.activeForeground':       '#94532c',
      'editorIndentGuide.background':            '#e7ddc9',
      'editorIndentGuide.activeBackground':      '#b8a685',
      'editorBracketMatch.background':           '#94532c26',
      'editorBracketMatch.border':               '#94532c66',
      'editorBracketHighlight.foreground1':      '#94532c',
      'editorBracketHighlight.foreground2':      '#b48235',
      'editorBracketHighlight.foreground3':      '#6b864a',
      'editorBracketHighlight.foreground4':      '#7a5a98',
      'editorBracketHighlight.foreground5':      '#3f6680',
      'editorBracketHighlight.foreground6':      '#a65a2a',
      'editorGutter.background':                 '#faf5ea',
      'editorWidget.background':                 '#faf5ea',
      'editorWidget.border':                     '#e7ddc9',
      'editorSuggestWidget.background':          '#faf5ea',
      'editorSuggestWidget.border':              '#e7ddc9',
      'editorSuggestWidget.selectedBackground':  '#efe6d5',
      'editorSuggestWidget.highlightForeground': '#94532c',
      'minimap.background':                      '#faf5ea',
      'scrollbarSlider.background':              '#94532c26',
      'scrollbarSlider.hoverBackground':         '#94532c40',
      'scrollbarSlider.activeBackground':        '#94532c60',
    },
  });
}

/** Read the current `[data-theme]` attribute and pick the right Monaco theme. */
export function suxaiThemeForMode(mode: 'dark' | 'light'): typeof SUXAI_DARK | typeof SUXAI_LIGHT {
  return mode === 'light' ? SUXAI_LIGHT : SUXAI_DARK;
}
